name: Yatopia Build Script

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - ver/1.16.1
  pull_request:
    paths-ignore:
      - '*.md'
    branches:
      - ver/1.16.1

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [14, 11, 8]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.4.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Pull Maven Cache
      uses: actions/cache@v2
      id: maven-cache
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - uses: s4u/maven-settings-action@v2.1.0
      name: Use ${{ matrix.java }} as the java target
      with:
        properties: '[{"maven.compiler.target": "${{ matrix.java }}"}]'
    - name: Setup Yatopia Project
      run: |
         git submodule update --init --recursive -f
         git config --global user.email "ci@github.com"
         git config --global user.name "Github CI"
         sudo chmod -R -f 777 scripts   
    - name: Build Maven Depends
      if: steps.maven-cache.outputs.cache-hit != 'true'
      run: |
         cd Tuinity
         ./tuinity jar
         cd ..//           
    - name: Build Yatopia
      run: |
        ./yatopia full
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Yatopia-${{ matrix.java }}
        path: yatopia-1.16.1-paperclip.jar
    - name: Deploy Release
      if: github.ref == 'refs/heads/ver/1.16.1'
      uses: WebFreak001/deploy-nightly@v1.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by github actions
      with:
        upload_url: https://uploads.github.com/repos/tr7zw/Yatopia/releases/28703947/assets{?name,label} # find out this value by opening https://api.github.com/repos/<owner>/<repo>/releases in your browser and copy the full "upload_url" value including the {?name,label} part
        release_id: 28703947 # same as above (id can just be taken out the upload_url, it's used to find old releases)
        asset_path: yatopia-1.16.1-paperclip.jar # path to archive to upload
        asset_name: Yatopia-1.16.1-JDK${{ matrix.java }}-paperclip.jar # name to upload the release as, use $$ to insert date (YYYYMMDD) and 6 letter commit hash
        asset_content_type: application/zip # required by GitHub API
        max_releases: 3 # optional, if there are more releases than this matching the asset_name, the oldest ones are going to be deleted
