name: CI

on: [push, pull_request]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [11, 8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1.3.0
      with:
        java-version: ${{ matrix.java }}
    - name: Pull Maven Cache
      uses: actions/cache@v1.1.2
      id: maven-cache
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Setup YAPFA Project
      run: |
         git submodule update --init -f
         git config --global user.email "ci@github.com"
         git config --global user.name "Github CI"
         sudo chmod -R -f 777 scripts
         cd Tuinity
         git submodule update --init --recursive -f
         cd ..//
    - name: Build Maven Depends
      if: steps.maven-cache.outputs.cache-hit != 'true'
      run: |
         cd Tuinity
         ./tuinity jar
         cd ..//           
    - name: Build YAPFA
      run: |
        ./yapfa paperclip
    - name: Upload Artifact
      uses: actions/upload-artifact@v2-preview
      with:
        name: YAPFA-${{ matrix.java }}
        path: target/YAPFA-1.16.1-paperclip.jar
