name: Yatopia Build Script

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - ver/1.16.3
      - ver/1.16.2
      - ver/1.16.1
  pull_request:
    paths-ignore:
      - '*.md'
    branches:
      - ver/1.16.3
      - ver/1.16.1
      - ver/1.16.2

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [14, 11, 8]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.4.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Pull Maven Cache
      uses: actions/cache@v2
      id: maven-cache
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - uses: s4u/maven-settings-action@v2.1.0
      name: Use ${{ matrix.java }} as the java target
      with:
        properties: '[{"maven.compiler.target": "${{ matrix.java }}"}]'
    - name: Setup Yatopia Project
      run: |
         git config --global user.email "ci@github.com"
         git config --global user.name "Github CI"
         sudo chmod -R -f 777 scripts
         ./yatopia init
#    - name: Build Maven Depends
#      if: steps.maven-cache.outputs.cache-hit != 'true'
#      run: |
#         cd Tuinity
#         ./tuinity jar
#         cd ..//
    - name: Build Yatopia
      run: |
        ./yatopia full
