name: Tuinity-Upstream

on:
  schedule:
  - cron: "*/60 */2 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 11
    - name: Update with Tuinity
      run: |
        git submodule init
        git submodule update --init --recursive
        git config --global user.email "ci@github.com"
        git config --global user.name "Github CI"
        yapfaDir=`pwd`
        cd Tuinity
        pwd
        git status
        git fetch
        git reset --hard origin
        cd ..
        ./patchPaper.sh
        cd Tuinity
        ./tuinity jar
        cd $yapfaDir
        ./yapfa patch
        ./yapfa rb
        ./yapfa patch
        ./yapfa build
        ./yapfa paperclip
        git add $(git rev-parse --show-toplevel)
        git commit -m "Update upstream"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update Upstream
          title: '[Automated] Tuinity updates'
          body: 'Fetch Upstream from https://github.com/Spottedleaf/Tuinity'
